### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by GrahamCampbell**
PSR-4 autoloading, fixed the demos, and fixed the tests on travis (you broke them before: https://travis-ci.org/jeremeamia/FunctionParser/builds/16966192).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @jeremeamia.

**Comment by GrahamCampbell** [comment]
Ping @jeremeamia.

**Comment by GrahamCampbell** [comment]
@jeremeamia Tagging a 1.0.0 release would be cool too, allowing people to use this as a stable dependency. Also, your wiki can be disabled since it's not in use. :)

**Comment by jeremeamia** [comment]
Sounds good.

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
